version: '3'

services:
    nginx:
      image: nginx:latest
      container_name: sf4_nginx
      ports:
        - 80:80
      volumes:
        - .:/code
        - .docker/nginx/:/etc/nginx/conf.d/
      depends_on:
        - php

    mysql:
      image: mysql:5
      container_name: sf4_mysql
      ports:
        - 3306:3306
      volumes:
        - .docker/data/db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: sf4
        MYSQL_USER: sf4
        MYSQL_PASSWORD: sf4

    php:
      build: .docker/php
      container_name: sf4_php
      volumes:
        - .:/code
      environment:
        - maildev_host=sf4_maildev
      depends_on:
        - maildev
        - mysql

    maildev:
      image: djfarrelly/maildev
      container_name: sf4_maildev
      ports:
        - 8001:80
